Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -19,7 +19,6 @@ jobs:
   setup_linux:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
-    continue-on-error: true
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
@@ -28,7 +27,10 @@ jobs:
         
       # Error Check
       - name: Run install.sh
+        continue-on-error: true
         run: ./install.sh linux
+#         if: succeeded() || failed()
+#         run: ./link.sh
 
       - name: Run link.sh
         run: ./link.sh
