cancel-in-progress

diff --git a/.github/workflows/setup.yml b/.github/workflows/setup.yml
--- a/.github/workflows/setup.yml
+++ b/.github/workflows/setup.yml
@@ -2,16 +2,20 @@
 
 name: CI
 
-# Controls when the action will run. 
+# Controls when the action will run.
 on:
   # Triggers the workflow on push or pull request events but only for the master branch
   push:
-    branches: [ master ]
+    branches: [master]
   pull_request:
-    branches: [ master ]
+    branches: [master]
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
@@ -24,24 +28,24 @@ jobs:
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
-        
+
       # Error Check
       - name: Run install.sh
         continue-on-error: true
-        run: ./install.sh 
-#         if: succeeded() || failed()
-#         run: ./link.sh
+        run: ./install.sh
+      #         if: succeeded() || failed()
+      #         run: ./link.sh
 
       - name: Run link.sh
         run: ./link.sh
-        
+
       - name: Run zsh
         run: zsh
-          
+
   setup_mac:
     # The type of runner that the job will run on
     runs-on: macos-latest
-      
+
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
@@ -50,10 +54,10 @@ jobs:
       # Error Check
       - name: Run install.sh
         continue-on-error: true
-        run: ./install.sh 
+        run: ./install.sh
 
       - name: Run link.sh
         run: ./link.sh
-        
+
       - name: Run zsh
         run: zsh
